import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Play, Sparkles, Users, Zap } from "lucide-react"
import { ImageUrls } from "@/lib/image-service"

export function HeroSection() {
  return (
    <section className="relative overflow-hidden py-16 md:py-24 lg:py-32">
      <div className="absolute inset-0 bg-gradient-to-br from-background via-background to-background/50 z-10" />
      <div className="absolute inset-0 opacity-30">
        <div className="absolute inset-0 bg-grid-white/5 [mask-image:linear-gradient(to_bottom,transparent,black)]" />
        <div className="absolute left-0 right-0 top-0 -z-10 m-auto h-[50vh] w-full bg-gradient-to-b from-zinc-950 to-background"></div>
        <div className="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80">
          <div
            className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-purple-800 to-purple-950 opacity-20 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
            style={{
              clipPath:
                "polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)",
            }}
          />
        </div>
      </div>
      <div className="container relative z-20">
        <div className="flex justify-center mb-8">
          <Badge variant="secondary" className="px-4 py-2 text-sm font-medium">
            <Sparkles className="h-4 w-4 mr-2" />
            Join 10,000+ creators and users making amazing AI art
          </Badge>
        </div>
        <div className="mx-auto max-w-4xl text-center">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl">
            Create <span className="text-primary bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">stunning AI images</span> with styles from top creators
          </h1>
          <p className="mt-6 text-lg sm:text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
            Pretty.af makes it effortless to generate on-brand, professional AI images. Browse unique styles from verified creators and start creating in seconds.
          </p>
          <div className="mt-8 flex flex-wrap justify-center gap-4 text-sm text-muted-foreground">
            <div className="flex items-center gap-2">
              <Zap className="h-4 w-4 text-primary" />
              <span>5 free generations</span>
            </div>
            <div className="flex items-center gap-2">
              <Users className="h-4 w-4 text-primary" />
              <span>1000+ unique styles</span>
            </div>
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" />
              <span>Professional quality</span>
            </div>
          </div>
          <div className="mt-10 flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" className="text-base px-8 py-6 h-auto" asChild>
              <Link href="/explore">
                <Play className="h-5 w-5 mr-2" />
                Start Creating Free
              </Link>
            </Button>
            <Button size="lg" variant="outline" className="text-base px-8 py-6 h-auto" asChild>
              <Link href="/creators">
                <Sparkles className="h-5 w-5 mr-2" />
                Become a Creator
              </Link>
            </Button>
          </div>
          <div className="mt-8 text-sm text-muted-foreground">
            <p>✨ No credit card required • 🎨 Start creating instantly • 💎 Premium styles available</p>
          </div>
        </div>
        <div className="mt-16 lg:mt-20">
          <div className="text-center mb-8">
            <h2 className="text-2xl font-semibold mb-2">See what's possible</h2>
            <p className="text-muted-foreground">Real images generated by our community</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 lg:gap-6">
            <div className="relative group">
              <div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-muted">
                <img
                  src={ImageUrls.styleImage('Cyberpunk Neon Dreams', 'cyberpunk')}
                  alt="Cyberpunk neon cityscape generated with Pretty.af"
                  className="object-cover w-full h-full transition-all duration-500 group-hover:scale-105"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                <div className="absolute bottom-4 left-4 right-4 text-white opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                  <p className="font-medium">Cyberpunk Neon</p>
                  <p className="text-sm text-white/80">by @neonartist</p>
                </div>
              </div>
            </div>
            <div className="relative group">
              <div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-muted">
                <img
                  src={ImageUrls.styleImage('Vintage Film Photography', 'vintage')}
                  alt="Vintage film photography style generated with Pretty.af"
                  className="object-cover w-full h-full transition-all duration-500 group-hover:scale-105"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                <div className="absolute bottom-4 left-4 right-4 text-white opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                  <p className="font-medium">Vintage Film</p>
                  <p className="text-sm text-white/80">by @retrovisuals</p>
                </div>
              </div>
            </div>
            <div className="relative group sm:col-span-2 lg:col-span-1">
              <div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-muted">
                <img
                  src={ImageUrls.styleImage('Abstract Fluid Waves', 'abstract')}
                  alt="Abstract wave art generated with Pretty.af"
                  className="object-cover w-full h-full transition-all duration-500 group-hover:scale-105"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                <div className="absolute bottom-4 left-4 right-4 text-white opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                  <p className="font-medium">Abstract Waves</p>
                  <p className="text-sm text-white/80">by @wavecreator</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
